//! MIME parsing, Unicode-safe sanitization, and look-alike detection for rusty-imap-mcp.
//!
//! Modules: `parse` (MIME + body extraction), `unicode` (scrubbing),
//! `output` (response shapes), `html` (ammonia-based sanitization),
//! `lookalike` (confusables-backed spoofing detection), `error`.

#![deny(missing_docs)]

pub mod error;
pub mod output;
pub mod parse;

mod html;
mod lookalike;
pub(crate) mod unicode;

#[cfg(any(test, feature = "test-support"))]
pub mod test_support;

pub use error::ContentError;
pub use output::{
    AttachmentMeta, Content, ContentMeta, MailingListInfo, SecurityWarning, SelectedHeader,
    Untrusted, WarningCode, WarningSeverity,
};
pub use parse::{RawPart, ThreadingHeaders, extract_threading_headers, walk_attachment_parts};
pub use parse::{parse_message, parse_message_with_headers};
// Sanctioned text-sanitization surface. The `unicode` module is crate-private;
// handlers reach these named entry points at the crate root rather than into
// the module internals, so the "sanitize every untrusted byte before it
// reaches the agent" policy is exposed as one curated set.
pub use unicode::{
    FilterResult, decode, filter_codepoints, normalize_line_endings, normalize_nfkc, sanitize,
    truncate_graphemes, truncate_graphemes_in_place,
};

/// Extract the `Message-ID` header from raw RFC 5322 bytes.
///
/// Thin wrapper around `mail_parser` so tool handlers do not need to
/// depend on `mail_parser` directly just to read one header off a
/// freshly-built message. Returns `None` when the input is not
/// parseable or when no `Message-ID` header is present.
#[must_use]
pub fn extract_message_id(raw: &[u8]) -> Option<String> {
    crate::parse::safe_parser::safe_parse(raw)
        .ok()
        .flatten()
        .and_then(|m| m.message_id().map(ToString::to_string))
}

/// Extract the RFC 2047-decoded `Subject` from raw RFC 5322 bytes via the
/// panic-catching, size-bounded [`safe_parse`](crate::parse) path.
///
/// The returned string is the *decoded* subject (encoded-words expanded),
/// so a caller echoing it into an outbound header MUST still strip control
/// characters: a decoded encoded-word can contain bare CR/LF that
/// `mail_parser` does not neutralize, which would enable header injection
/// into a re-sent message. Returns `None` when the input is unparsable or
/// carries no `Subject`.
#[must_use]
pub fn extract_subject(raw: &[u8]) -> Option<String> {
    crate::parse::safe_parser::safe_parse(raw)
        .ok()
        .flatten()
        .and_then(|m| m.subject().map(ToString::to_string))
}

/// Sanitized outbound HTML plus the warnings raised while stripping it.
#[derive(Debug, Clone)]
pub struct OutboundHtml {
    /// Ammonia-sanitized HTML: tag-allowlisted, scripts/styles/iframes and
    /// remote content removed, `javascript:` URLs dropped. Safe to place in a
    /// `text/html` part.
    pub body_html: String,
    /// Warnings describing what the sanitizer removed or flagged (stripped
    /// scripts, remote images, hidden content, link/text mismatches), so a
    /// caller can surface that the agent's HTML was altered before sending.
    pub warnings: Vec<SecurityWarning>,
}

/// Sanitize agent-authored HTML for an *outbound* message body.
///
/// Runs the caller's HTML through the same tag-allowlist ammonia pipeline used
/// for inbound mail (`crate::html`'s `sanitize`), so the server never emits
/// agent-supplied `<script>`, event handlers, remote images, or `javascript:`
/// URLs. Only the sanitized HTML and the strip warnings are returned; the
/// inbound-only `body_text` / `anchor_hrefs` are dropped. Callers must still
/// send a `text/plain` alternative alongside the returned HTML.
///
/// # Errors
///
/// Returns [`ContentError::LimitExceeded`] when `raw` exceeds the 1 MiB HTML
/// body cap.
pub fn sanitize_outbound_html(raw: &str) -> Result<OutboundHtml, ContentError> {
    let result = crate::html::sanitize(raw.as_bytes(), Some("utf-8"))?;
    Ok(OutboundHtml {
        body_html: result.body_html,
        warnings: result.warnings,
    })
}

/// Compile-time TR39 confusables map, generated by build.rs from
/// `data/confusables.txt`. Consumed by `lookalike::classify_domain`.
#[expect(
    clippy::unicode_not_nfc,
    reason = "generated TR39 MA table preserves source codepoints verbatim"
)]
#[expect(
    clippy::unreadable_literal,
    reason = "phf_codegen emits raw u64 hash seeds"
)]
mod confusables {
    include!(concat!(env!("OUT_DIR"), "/confusables.rs"));
}

#[cfg(test)]
#[expect(clippy::expect_used, reason = "tests may expect on constructed values")]
mod confusables_tests {
    use crate::confusables::CONFUSABLES;

    #[test]
    fn confusables_map_contains_cyrillic_a_to_latin_a() {
        // U+0430 CYRILLIC SMALL LETTER A → "a" (U+0061)
        let target = CONFUSABLES
            .get(&'\u{0430}')
            .expect("cyrillic a should map via TR39");
        assert_eq!(*target, "a");
    }

    #[test]
    fn confusables_map_size_nontrivial() {
        // Sanity: Unicode 16 has > 6000 MA rows.
        assert!(
            CONFUSABLES.len() > 5000,
            "confusables map is suspiciously small: {}",
            CONFUSABLES.len()
        );
    }
}

#[cfg(test)]
#[expect(clippy::unwrap_used, reason = "tests")]
mod sanitize_outbound_html_tests {
    use super::sanitize_outbound_html;

    #[test]
    fn strips_script_and_warns() {
        let out = sanitize_outbound_html("<p>hi</p><script>alert(1)</script>").unwrap();
        assert!(!out.body_html.contains("<script"));
        assert!(!out.body_html.contains("alert"));
        assert!(out.body_html.contains("hi"));
        assert!(
            !out.warnings.is_empty(),
            "stripping a script should raise a warning",
        );
    }

    #[test]
    fn drops_javascript_url() {
        let out = sanitize_outbound_html("<a href=\"javascript:alert(1)\">x</a>").unwrap();
        assert!(!out.body_html.contains("javascript:"));
    }

    #[test]
    fn strips_remote_image_src() {
        let out = sanitize_outbound_html("<img src=\"https://evil.example/track.gif\">").unwrap();
        assert!(!out.body_html.contains("evil.example"));
        assert!(!out.body_html.contains("src="));
    }

    #[test]
    fn preserves_safe_markup() {
        let out = sanitize_outbound_html("<p>Hello <strong>world</strong></p>").unwrap();
        assert!(out.body_html.contains("<strong>"));
        assert!(out.body_html.contains("world"));
    }

    #[test]
    fn rejects_oversize_input() {
        let big = "x".repeat(1024 * 1024 + 1);
        assert!(sanitize_outbound_html(&big).is_err());
    }
}

#[cfg(test)]
#[expect(clippy::expect_used, reason = "tests")]
mod extract_message_id_tests {
    use super::extract_message_id;

    #[test]
    fn extract_returns_message_id_when_header_present() {
        // Kills all three wholesale stubs at extract_message_id (None,
        // Some(""), Some("xyzzy")). A constructed message with a
        // distinctive Message-ID round-trips through mail_parser to
        // a non-empty Some that contains the id substring.
        let raw = b"From: a@example\r\n\
                    Message-ID: <abc-123@example.com>\r\n\
                    \r\n\
                    body";
        let id = extract_message_id(raw).expect("Message-ID must be extracted");
        assert!(
            id.contains("abc-123@example.com"),
            "expected id to contain abc-123@example.com, got {id:?}",
        );
    }
}
