//! MIME parsing, Unicode-safe sanitization, and look-alike detection for rusty-imap-mcp.
//!
//! Modules: `parse` (MIME + body extraction), `unicode` (scrubbing),
//! `output` (response shapes), `html` (ammonia-based sanitization),
//! `lookalike` (confusables-backed spoofing detection), `error`.

#![deny(missing_docs)]

pub mod error;
pub mod output;
pub mod parse;

mod html;
mod lookalike;
pub(crate) mod unicode;

#[cfg(any(test, feature = "test-support"))]
pub mod test_support;

pub use error::ContentError;
pub use output::{
    AttachmentMeta, Content, ContentMeta, MailingListInfo, SecurityWarning, Untrusted, WarningCode,
    WarningSeverity,
};
pub use parse::parse_message;
pub use parse::{RawPart, ThreadingHeaders, extract_threading_headers, walk_attachment_parts};
// Sanctioned text-sanitization surface. The `unicode` module is crate-private;
// handlers reach these named entry points at the crate root rather than into
// the module internals, so the "sanitize every untrusted byte before it
// reaches the agent" policy is exposed as one curated set.
pub use unicode::{
    FilterResult, decode, filter_codepoints, normalize_line_endings, normalize_nfkc, sanitize,
    truncate_graphemes, truncate_graphemes_in_place,
};

/// Extract the `Message-ID` header from raw RFC 5322 bytes.
///
/// Thin wrapper around `mail_parser` so tool handlers do not need to
/// depend on `mail_parser` directly just to read one header off a
/// freshly-built message. Returns `None` when the input is not
/// parseable or when no `Message-ID` header is present.
#[must_use]
pub fn extract_message_id(raw: &[u8]) -> Option<String> {
    crate::parse::safe_parser::safe_parse(raw)
        .ok()
        .flatten()
        .and_then(|m| m.message_id().map(ToString::to_string))
}

/// Extract the RFC 2047-decoded `Subject` from raw RFC 5322 bytes via the
/// panic-catching, size-bounded [`safe_parse`](crate::parse) path.
///
/// The returned string is the *decoded* subject (encoded-words expanded),
/// so a caller echoing it into an outbound header MUST still strip control
/// characters: a decoded encoded-word can contain bare CR/LF that
/// `mail_parser` does not neutralize, which would enable header injection
/// into a re-sent message. Returns `None` when the input is unparsable or
/// carries no `Subject`.
#[must_use]
pub fn extract_subject(raw: &[u8]) -> Option<String> {
    crate::parse::safe_parser::safe_parse(raw)
        .ok()
        .flatten()
        .and_then(|m| m.subject().map(ToString::to_string))
}

/// Compile-time TR39 confusables map, generated by build.rs from
/// `data/confusables.txt`. Consumed by `lookalike::classify_domain`.
#[expect(
    clippy::unicode_not_nfc,
    reason = "generated TR39 MA table preserves source codepoints verbatim"
)]
#[expect(
    clippy::unreadable_literal,
    reason = "phf_codegen emits raw u64 hash seeds"
)]
mod confusables {
    include!(concat!(env!("OUT_DIR"), "/confusables.rs"));
}

#[cfg(test)]
#[expect(clippy::expect_used, reason = "tests may expect on constructed values")]
mod confusables_tests {
    use crate::confusables::CONFUSABLES;

    #[test]
    fn confusables_map_contains_cyrillic_a_to_latin_a() {
        // U+0430 CYRILLIC SMALL LETTER A → "a" (U+0061)
        let target = CONFUSABLES
            .get(&'\u{0430}')
            .expect("cyrillic a should map via TR39");
        assert_eq!(*target, "a");
    }

    #[test]
    fn confusables_map_size_nontrivial() {
        // Sanity: Unicode 16 has > 6000 MA rows.
        assert!(
            CONFUSABLES.len() > 5000,
            "confusables map is suspiciously small: {}",
            CONFUSABLES.len()
        );
    }
}

#[cfg(test)]
#[expect(clippy::expect_used, reason = "tests")]
mod extract_message_id_tests {
    use super::extract_message_id;

    #[test]
    fn extract_returns_message_id_when_header_present() {
        // Kills all three wholesale stubs at extract_message_id (None,
        // Some(""), Some("xyzzy")). A constructed message with a
        // distinctive Message-ID round-trips through mail_parser to
        // a non-empty Some that contains the id substring.
        let raw = b"From: a@example\r\n\
                    Message-ID: <abc-123@example.com>\r\n\
                    \r\n\
                    body";
        let id = extract_message_id(raw).expect("Message-ID must be extracted");
        assert!(
            id.contains("abc-123@example.com"),
            "expected id to contain abc-123@example.com, got {id:?}",
        );
    }
}
